catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import home, contacts, category_product, categories, create_product
from config import settings
from django.conf.urls.static import static

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('categories/', categories, name='categories'),
    path('contacts/', contacts, name='contacts'),
    path('<int:pk>/category_product/', category_product, name='category_product'),
    path('create_product/', create_product, name='create_product')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog'))
]
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
               + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

catalog/models.py
from django.db import models

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=150, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=150, verbose_name='описание')
    preview = models.ImageField(upload_to='preview/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    date_creation = models.DateTimeField(verbose_name='дата создания')
    date_last_change = models.DateTimeField(verbose_name='дата последнего изменения')

    def __str__(self):
        return f'Название: {self.name} Категория: {self.category}  Цена: {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('price',)

catalog/forms.py
from django import forms
from catalog.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'preview', 'category', 'price', 'date_creation', 'date_last_change']

catalog/views.py
from datetime import datetime

from django.shortcuts import render

from catalog.models import Product, Category
from catalog.forms import ProductForm

# Create your views here.

def home(request):
    context = {
        'object_list': Product.objects.all()[:3],
        'title': 'Топ товаров'
    }

    return render(request, 'catalog/home.html', context)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name}, {phone}, {message}')
    return render(request, 'catalog/contacts.html')


def categories(request):
    context = {
        'object_list': Category.objects.all(),
        'title': 'Категории'
    }

    return render(request, 'catalog/categories.html', context)


def category_product(request, pk):
    category_item = Category.objects.get(id=pk)
    context = {
        'object_list': Product.objects.filter(category_id=pk),
        'title': category_item.name,
        'description': category_item.description[:100]
    }
    return render(request, 'catalog/category_product.html', context)


def create_product(request):
    context = {
        'object_list': Category.objects.all()
    }
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'catalog/create_product.html', context)  # Перенаправьте на нужную страницу после сохранения
    else:
        form = ProductForm()
        return render(request, 'catalog/create_product.html', {'form': form})

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/docs.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">Главная</a></li>
                <li><a href="{% url 'catalog:contacts' %}" class="nav-link px-2 text-white">Контакты</a></li>
                <li><a href="{% url 'catalog:categories' %}" class="nav-link px-2 text-white">Каталог</a></li>
                <li><a href="{% url 'catalog:create_product'%}" class="nav-link px-2 text-white">Добавить товар </a></li>
                <li><a href="#" class="nav-link px-2 text-white"></a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Поиск..." aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-outline-light me-2">Вход</button>
                <button type="button" class="btn btn-warning">Регистрация</button>
            </div>
        </div>
    </div>
</header>

<div class="container ">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">SkyStore</h1>
            <p class="fs-5 text-body-secondary">{{ title }}</p>
        </div>
    </header>
    <main class="row">
        <div class="row text-center">
            {% block content %}
            {% endblock %}
        </div>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-10 fw-normal text-body-emphasis">F.A.Q.</h1>

            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Как купить?
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample"
                         style="">
                        <div class="accordion-body">
                            <strong>This is the first item's accordion body.</strong> It is shown by default, until the
                            collapse plugin adds the appropriate classes that we use to style each element. These
                            classes control the overall appearance, as well as the showing and hiding via CSS
                            transitions. You can modify any of this with custom CSS or overriding our default variables.
                            It's also worth noting that just about any HTML can go within the
                            <code>.accordion-body</code>, though the transition does limit overflow.
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Как заказать?
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample"
                         style="">
                        <div class="accordion-body">
                            <strong>This is the second item's accordion body.</strong> It is hidden by default, until
                            the collapse plugin adds the appropriate classes that we use to style each element. These
                            classes control the overall appearance, as well as the showing and hiding via CSS
                            transitions. You can modify any of this with custom CSS or overriding our default variables.
                            It's also worth noting that just about any HTML can go within the
                            <code>.accordion-body</code>, though the transition does limit overflow.
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Какая гарантия?
                        </button>
                    </h2>
                    <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample"
                         style="">
                        <div class="accordion-body">
                            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the
                            collapse plugin adds the appropriate classes that we use to style each element. These
                            classes control the overall appearance, as well as the showing and hiding via CSS
                            transitions. You can modify any of this with custom CSS or overriding our default variables.
                            It's also worth noting that just about any HTML can go within the
                            <code>.accordion-body</code>, though the transition does limit overflow.
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Example Code -->
        </div>
    </main>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html' %}

{% block content %}
{% for object in object_list %}
<div class="col-4">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body">
            <p>{{ object.description }}</p>
            <div>
                <p>
                    <a href="{% url 'catalog:category_product' object.pk %}" type="button"
                       class="h-100 btn btn-lg btn-secondary text-grey">Перейти к товарам
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/category_product.html
{% extends 'catalog/base.html' %}

{% block content %}
{% for object in object_list %}
    {% include 'catalog/includes/inc_products.html' %}
{% endfor %}
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/create_product.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="form-floating">
    {% csrf_token %}
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" class="form-control" name="name" maxlength="50" required id="id_name"
               placeholder="Наименование">
    </div>


    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" name="description" maxlength="150" required id="id_description" placeholder="Описание">
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="file" name="preview" accept="media/image/" id="id_preview" placeholder="Изображение">
    </div>
    <div class="input-group pricing-header pb-md-4">
        <label for="id_category">Категория:</label>
        <select name="category" required id="id_category">
            <option value="" selected>---------</option>
            {% for object in object_list %}-->
            <option value="{{ object.id }}">{{ object.name }}</option>
            {% endfor %}

<!--            <option value="1">название: Ноутбуки описание: Многофункциональное устройство для работы и развлечения-->
<!--            </option>-->

<!--            <option value="3">название: Портативные колонки описание: Устройство для прослушивания ваших любимых треков-->
<!--                в хорошем качестве-->
<!--            </option>-->

<!--            <option value="2">название: Смартфоны описание: Компактное устройсво с огромным функционалом, которое всегда-->
<!--                под рукой-->
<!--            </option>-->

        </select>
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="number" name="price" required id="id_price" placeholder="Цена за покупку">
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" name="date_creation" required id="id_date_creation" placeholder="Дата создания:">
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" name="date_last_change" required id="id_date_last_change"
               placeholder="Дата последнего изменения:">
    </div>
    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
</form>

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <input type="text" name="name" class="form-control" id="name" placeholder="Название товара" required>-->
<!--    </div>-->

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <label class="input-group-text" for="inputGroupSelect01">Категория</label>-->
<!--        <select name='category' class="form-select" id="inputGroupSelect01">-->
<!--            <option selected>...</option>-->
<!--            {% for object in object_list %}-->
<!--            <option name='category' value="{{ object.name }}">{{ object.name }}</option>-->
<!--            {% endfor %}-->
<!--        </select>-->
<!--    </div>-->
<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <input type="text" name="price" class="form-control" id="price" placeholder="Цена" required>-->
<!--    </div>-->

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <input type="file" class="form-control" id="image" name="image">-->
<!--    </div>-->

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <span class="input-group-text p-3 pricing-header pb-md-4 mx-auto text-center">Добавьте описание</span>-->
<!--        <textarea class="form-control" aria-label="With textarea" id="description" name="description" required></textarea>-->
<!--    </div>-->
<!--    <div class="col-1">-->
<!--        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>-->
<!--    </div>-->
<!--</form>-->
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.price }} руб</h2>
                <p>{{ object.description }}</p>
                <p>{{ object.preview }}</p>
                <div>
                    <p>
                        <button type="button" class="h-100 btn btn-lg btn-secondary text-grey">Посмотреть товар
                        </button>
                    </p>
                </div>
                <div>
                    <p>
                        <button type="button" class="h-100 btn btn-lg btn-success text-white">Купить
                        </button>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/includes/inc_products.html
{% load my_tags %}
<style>
    img {
        width: 300px;
        height: 200px;
    }
</style>
<div class="col-4">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body">
            <img src="{{ object.preview | my_media}}" />
            <h2 class="card-title pricing-card-title">{{ object.price }} руб</h2>
            <p>{{ object.description }}</p>
            <div>
                <p>
                    <button type="button" class="h-100 btn btn-lg btn-secondary text-grey">Посмотреть товар
                    </button>
                </p>
            </div>
            <div>
                <p>
                    <button type="button" class="h-100 btn btn-lg btn-success text-white">Купить
                    </button>
                </p>
            </div>
        </div>
    </div>
</div>